case class Book(title: String, authors: String*)

val books = List(
  Book("To Kill a Mockingbird", "Harper Lee"),
  Book("1984", "George Orwell"),
  Book("Pride and Prejudice", "Jane Austen"),
  Book("The Great Gatsby", "F. Scott Fitzgerald"),
  Book("Moby Dick", "Herman Melville"),
  Book("War and Peace", "Leo Tolstoy"),
  Book("The Catcher in the Rye", "J.D. Salinger"),
  Book("The Lord of the Rings", "J.R.R. Tolkien"),
  Book("The Hobbit", "J.R.R. Tolkien"),
  Book("Brave New World", "Aldous Huxley"),
  Book("The Picture of Dorian Gray", "Oscar Wilde"),
  Book("The Adventures of Sherlock Holmes", "Arthur Conan Doyle"),
  Book("Dracula", "Bram Stoker"),
  Book("The Count of Monte Cristo", "Alexandre Dumas"),
  Book("Great Expectations", "Charles Dickens"),
  Book("The Brothers Karamazov", "Fyodor Dostoevsky"),
  Book("Crime and Punishment", "Fyodor Dostoevsky"),
  Book("Wuthering Heights", "Emily Brontë"),
  Book("Jane Eyre", "Charlotte Brontë"),
  Book("Anna Karenina", "Leo Tolstoy"),
  Book("Frankenstein", "Mary Shelley"),
  Book("The Odyssey", "Homer"),
  Book("The Iliad", "Homer"),
  Book("Les Misérables", "Victor Hugo"),
  Book("Ulysses", "James Joyce"),
  Book("One Hundred Years of Solitude", "Gabriel Garcia Marquez"),
  Book("The Divine Comedy", "Dante Alighieri"),
  Book("Don Quixote", "Miguel de Cervantes"),
  Book("Madame Bovary", "Gustave Flaubert"),
  Book("The Three Musketeers", "Alexandre Dumas"),
  Book("The Metamorphosis", "Franz Kafka"),
  Book("Fahrenheit 451", "Ray Bradbury"),
  Book("Lolita", "Vladimir Nabokov"),
  Book("Heart of Darkness", "Joseph Conrad"),
  Book("The Stranger", "Albert Camus"),
  Book("Catch-22", "Joseph Heller"),
  Book("The Old Man and the Sea", "Ernest Hemingway"),
  Book("A Tale of Two Cities", "Charles Dickens"),
  Book("The Grapes of Wrath", "John Steinbeck"),
  Book("Slaughterhouse-Five", "Kurt Vonnegut"),
  Book("The Sound and the Fury", "William Faulkner"),
  Book("Beloved", "Toni Morrison"),
  Book("Invisible Man", "Ralph Ellison"),
  Book("The Sun Also Rises", "Ernest Hemingway"),
  Book("The Bell Jar", "Sylvia Plath"),
  Book("Gone with the Wind", "Margaret Mitchell"),
  Book("The Call of the Wild", "Jack London"),
  Book("White Fang", "Jack London")
)
